### ISSUE TITLE
With only one GPU, how to run the test?

### ISSUE THREAD

**Issue by KaqiKaqi** [huicongzhang/BSSTNet#7]
I'm not quite familiar with distributed training or test. So if I only want to test the pretrained model, what should I do?
I got the following error

```
2024-11-18 16:00:08,848 INFO: Network [BSST] is created.
Traceback (most recent call last):
Traceback (most recent call last):
  File "basicsr/test.py", line 47, in <module>
  File "basicsr/test.py", line 47, in <module>
        test_pipeline(root_path)test_pipeline(root_path)

  File "basicsr/test.py", line 35, in test_pipeline
  File "basicsr/test.py", line 35, in test_pipeline
    model = build_model(opt)
    model = build_model(opt)  File "/home/ur/data/github/BSSTNet/basicsr/models/__init__.py", line 26, in build_model

  File "/home/ur/data/github/BSSTNet/basicsr/models/__init__.py", line 26, in build_model
    model = MODEL_REGISTRY.get(opt['model_type'])(opt)
      File "/home/ur/data/github/BSSTNet/basicsr/models/Video_BSST_model.py", line 45, in __init__
model = MODEL_REGISTRY.get(opt['model_type'])(opt)
  File "/home/ur/data/github/BSSTNet/basicsr/models/Video_BSST_model.py", line 45, in __init__
    self.net_g = self.model10_to_device(self.net_g)
  File "/home/ur/data/github/BSSTNet/basicsr/models/Video_BSST_model.py", line 120, in model10_to_device
    self.net_g = self.model10_to_device(self.net_g)
  File "/home/ur/data/github/BSSTNet/basicsr/models/Video_BSST_model.py", line 120, in model10_to_device
    net = DistributedDataParallel(
  File "/home/ur/miniforge3/envs/BSSTNet/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 646, in __init__
    net = DistributedDataParallel(
  File "/home/ur/miniforge3/envs/BSSTNet/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 646, in __init__
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/home/ur/miniforge3/envs/BSSTNet/lib/python3.8/site-packages/torch/distributed/utils.py", line 89, in _verify_param_shape_across_processes
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/home/ur/miniforge3/envs/BSSTNet/lib/python3.8/site-packages/torch/distributed/utils.py", line 89, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1191, invalid usage, NCCL version 2.10.3
ncclInvalidUsage: This usually reflects invalid usage of NCCL library (such as too many async ops, too many collectives at once, mixing streams in a group, etc).
    return dist._verify_params_across_processes(process_group, tensors, logger)
RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1191, invalid usage, NCCL version 2.10.3
ncclInvalidUsage: This usually reflects invalid usage of NCCL library (such as too many async ops, too many collectives at once, mixing streams in a group, etc).
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 15498) of binary: /home/ur/miniforge3/envs/BSSTNet/bin/python
Traceback (most recent call last):
  File "/home/ur/miniforge3/envs/BSSTNet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ur/miniforge3/envs/BSSTNet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ur/miniforge3/envs/BSSTNet/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/ur/miniforge3/envs/BSSTNet/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/ur/miniforge3/envs/BSSTNet/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/ur/miniforge3/envs/BSSTNet/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/home/ur/miniforge3/envs/BSSTNet/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ur/miniforge3/envs/BSSTNet/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
basicsr/test.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-11-18_16:00:12
  host      : ur-System-Product-Name
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 15499)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-11-18_16:00:12
  host      : ur-System-Product-Name
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 15498)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by AweXCHO** [comment]
I encountered the same situation. By changing the "os.environ["CUDA_VISIBLE_DEVICES"] = "0"" in basicsr/train(or test).py, the code can run with one GPU.

**Comment by huicongzhang** [comment]
Hi
Sorry, this was our mistake. We shouldn't have specified the number of GPUs in the [test.py line 2](https://github.com/huicongzhang/BSSTNet/blob/d40dd4ad747e7c416af436774b28af5ee5579c16/basicsr/test.py#L2) . You can comment out that line and use the following command for single GPU testing:
`scripts/dist_test.sh 1 options/test/BSST/gopro_BSST.yml`
We have fixed this issue in the code.
